name: locker_app
description: "Open Locker App"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  go_router: ^14.8.0
  shared_preferences: ^2.5.2

  openapi_generator: ^6.1.0
  openapi_generator_annotations: ^6.1.0
  build_runner: ^2.4.15

  locker_api:
    path: ./api/locker_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
